config/routes.rb
  types_of_user         = Regexp.new("(#{User::TYPES.map(&:last).map(&:tableize).join('|')})")
  orders_of_user        = Regexp.new("(#{User::ORDERS.join('|')})")

  estado = Regexp.new('[a-z]{2}')
  cidade = Regexp.new('[a-zA-Z\-]+')

  match "/*robots.txt", :to => redirect("/robots.txt")

  #=================================================#
  #  Admin
  #=================================================#
  match "/admin", :to => "admin/painel#index", :as => "admin"

  namespace :admin do

    resources :macro_tags

    resources :tags do
      collection do
        get :maistags
        post :set_tag_name
        post :novastags
        get :transferencia
        post :transferencia_post
        post :transfere_drag
        match :separar
      end
    end
    resources :topicos do
      member do
        post :comment_destroy
      end
    end
    resources :configuracoes do
      collection do
        get :update_check_box
        post :salvar
      end
    end
    resources :comentarios
  end

  #=============================================================================================#
  #  Aplicação para o USUÁRIO: Login, logout, cadastro, confirmação, perfil, observatorio etc.
  #=============================================================================================#

  devise_for :users,
    :controllers => {
      :registrations => "devise/custom/registrations",
      :passwords => "devise/custom/passwords",
      :sessions => "devise/custom/sessions",
      :omniauth_callbacks => "omniauth_callbacks"
    }

  match "/usuario/completar_cadastro" => "users#complete", :as => "completar_cadastro"
  match "/vincular/:user_id_criptografado" => "users#vincular", :as => "vincular"
  match "/solicitar_vinculacao/:organizacao_id" => "users#solicitar_vinculacao", :as => "solicitar_vinculacao"
  match "/usuarios/solicitar_cadastro_entidade" => "users#solicitar_cadastro_entidade", :as => "solicitar_cadastro_entidade"
  match "/users/:id/waiting_for_confirmation" => "users#waiting_for_confirmation", :as => "waiting_for_confirmation"
  match "/users/save" => "users#save"

  # Navegação por usuários
  match "/usuarios(/:user_type)(/estado/:estado_abrev)(/cidade/:cidade_slug)(/bairro/:bairro_id)(/:order)" => "users#index",
    :constraints => {
      :user_type => types_of_user,
      :estado_abrev => estado,
      :cidade_slug => cidade,
      :bairro_id => /\d+/,
      :order => orders_of_user
    },
    :as => "usuarios"

  # Perfil do usuário: dados pessoais, local, avatar, tópicos, comentários, funcionários, etc.
  match "/perfil/:id" => "users#show", :constraints => { :id => /\d+/ }, :as => "perfil"
  match "/perfil/:id.:format" => "users#show", :constraints => { :id => /\d+/ }, :as => "perfil_rss"
  match "/perfil/:id.:format" => "users#show", :constraints => { :id => /\d+/ }, :as => "perfil_json"
  match "/perfil/:id/mensagem" => "users#mensagem", :constraints => { :id => /\d+/ }, :as => "perfil_mensagem"

  match "/perfil/:id/propostas" => "users#show", :type => "propostas", :constraints => { :id => /\d+/ }, :as => "perfil_propostas"
  match "/perfil/:id/problemas" => "users#show", :type => "problemas", :constraints => { :id => /\d+/ }, :as => "perfil_problemas"
  match "/perfil/:id/comentarios" => "users#show", :type => "comments", :constraints => { :id => /\d+/ }, :as => "perfil_comentarios"
  match "/perfil/:id/apoios" => "users#show", :type => "adesoes", :constraints => { :id => /\d+/ }, :as => "perfil_apoios"
  match "/perfil/:id/seguindo" => "users#show", :type => "seguidos", :constraints => { :id => /\d+/ }, :as => "perfil_seguindo"

  match "/perfil/dados_basicos" => "users#edit", :as => "edit_user"
  match "/perfil/localizacao" => "users#localizacao"
  match "/perfil/avatar" => "avatar#new", :as => "new_avatar"
  match "/perfil/avatar/resize" => "avatar#resize"
  match "/perfil/avatar/salvar" => "avatar#create"
  match "/perfil/avatar/remover" => "avatar#destroy"
  match "/perfil/descadastrar" => "users#descadastrar", :as => "descadastrar"
  match "/perfil/confirma_descadastro" => "users#confirma_descadastro", :as => "confirma_descadastro"

  # Meu Observatório
  match "/meu-observatorio/novo" => "observatorios#new", :as => "novo_observatorio"
  match "/meu-observatorio/criar" => "observatorios#create", :as => "criar_observatorio"
  match "/meu-observatorio/editar" => "observatorios#edit", :as => "editar_observatorio"
  match "/meu-observatorio/salvar" => "observatorios#salvar", :as => "salvar_observatorio"
  match "/meu-observatorio/comentarios(/:page)" => "observatorios#comentarios", :as => "observatorio_comentarios"
  match "/meu-observatorio/apoios(/:page)" => "observatorios#apoios", :as => "observatorio_apoios"
  match "/meu-observatorio(/:page)" => "observatorios#index", :as => "observatorio"
  match "/meu-observatorio/:action/:id" => "observatorios"

  #==============================================#
  #   Tópicos
  #==============================================#

  match "/:topico_type(/estado/:estado_abrev)(/cidade/:cidade_slug)(/bairro/:bairro_id)(/tags/:tag_id)(/de/:user_type)(/:order(/:rss))(/:page)" => "topicos#index",
    :constraints => {
      :topico_type  => types_of_topico,
      :estado_abrev => estado,
      :cidade_slug  => cidade,
      :bairro_id    => /\d+/,
      :tag_id       => /\d+/,
      :user_type    => types_of_user,
      :order        => orders_of_topico,
      :rss          => feeds_of_topico,
      :page         => /\d+/
    },
    :defaults => {
      :topico_type => "topicos"
    },
    :as => "topicos"

  match "/topicos/mostrar_similares" => "topicos#mostrar_similares", :as => "topico_mostrar_similares"

  # Novo tópico
  match "/topicos/criar/:type" => "topicos#new", :via => :get, :as => "novo_topico"
  match "/topicos/criar/:type/localizar" => "topicos#new_localizar", :via => :post, :as => "localizar_novo_topico"
  match '/competitions/:competition_id/proposal/new' => 'topicos#new', :type => "proposta", :as => :new_competition_proposal
  match "/topicos/salvar" => "topicos#create", :as => "criar_topico"

  # Tópico
  match "/topico/:topico_slug" => "topicos#show", :as => "topico"
  match "/topico/:topico_slug/editar" => "topicos#edit", :as => "editar_topico"
  match "/topico/:topico_slug/salvar" => "topicos#update", :as => "salvar_topico"

  match "/topico/:topico_slug/aderir" => "topicos#aderir", :as => "aderir"
  match "/topico/:topico_slug/seguir" => "topicos#seguir", :as => "seguir"

  # Localização de tópico
  match "/topico/:topico_slug/localizacao" => "topicos#localizacao", :as => "topico_localizacao"

  # Editar Tags de tópico
  match "/topico/:topico_slug/tags" => "topicos#tags", :as => "topico_localizacao"
  match "/topico/:topico_slug/tags_by_link" => "topicos#tags_by_link", :as => "topico_localizacao"

  # Imagens de tópico
  match "/topico/:topico_slug/imagens" => "imagens#index", :as => "topico_imagens"
  match "/topico/:topico_slug/imagens/nova" => "imagens#create", :as => "topico_nova_imagem"
  match "/topico/:topico_slug/imagens/editar/:id" => "imagens#edit", :as => "topico_editar_imagem"
  match "/topico/:topico_slug/imagens/remover/:id" => "imagens#destroy", :as => "topico_remover_imagem"

  # Links de tópico
  match "/topico/:topico_slug/links" => "links#index", :as => "topico_links"
  match "/topico/:topico_slug/links/novo" => "links#create", :as => "topico_novo_link"
  match "/topico/:topico_slug/links/remover/:id" => "links#destroy", :as => "topico_remover_link"

  # Denunciar
  match "/topico/:topico_slug/denunciar" => "topicos#denunciar", :as => "topico_denunciar"

  # Comments
  match "/comments/processar" => "comments#processar", :as => "processar_comment"
  match "/comments/create" => "comments#create", :as => "create_comment"
  match "/comments/set_comentario_body/:id" => "comments#set_comentario_body"

  #======================================#
  #  Competitions
  #======================================#
  get '/competitions/:id(/fase/:phase(/tags/:tag_id))(/:order)(/page/:page)' => 'competitions#show',
    :constraints => CompetitionConstraint, :as => :competition

  resources :competitions, :only => [:index] do
    resources :inspirations

    member do
      get 'regulation'
      get 'prizes'
      get 'partners'
    end
  end

  #======================================#
  #  Joining Topics
  #======================================#
  match "/joining_topics/new/:topico_id", :controller => "joining_topics", :action => "new",
    :constraints => {:topico_id => /\d+/},
    :as => :new_joining_topic

  resources :joining_topics, :only => [:show, :create] do
    member do
      get :preview

      get :title_edit
      put :title_update

      get :description_edit
      put :description_update

      put :suggest
      put :reject
      put :aprove
    end
  end

  #======================================#
  #  General
  #======================================#

  # Tags
  match "/tags/auto_complete_responder" => "tags#auto_complete_responder", :as => "auto_complete_responder_tags"

  # Busca do Google
  match "/busca-google" => "busca#index", :as => "busca_google"

  # Static pages
  match "/static_pages/:name" => 'static_pages#show', :as => :static_page, :format => false

  # Locais
  match "/locais/cidades_li_for_ul" => "locais#cidades_li_for_ul"
  match "/locais/bairros_li_for_ul" => "locais#bairros_li_for_ul"
  match "/locais/cidades_options_for_select(/:first_option)" => "locais#cidades_options_for_select", :as => :cidades_options_for_select
  match "/locais/bairros_options_for_select(/:first_option)" => "locais#bairros_options_for_select", :as => :bairros_options_for_select

  # Conteúdos estáticos
  match "/tour" => "home#tour", :as => "tour"
  match "/fale-conosco" => "home#fale_conosco", :as => "fale_conosco"

  # Lista todos as cidades e estados
  match "/cidades" => "locais#cidades", :as => "cidades"
  match "/temas" => "home#temas", :as => "temas"

  # Raiz do site
  root :to => 'home#index'

app/models/competition.rb
class Competition < ActiveRecord::Base
  include Activities::Competition
  PHASES = [:inspiration_phase, :proposals_phase, :support_phase, :joining_phase, :announce_phase].freeze
  ORDERS = ["recentes", "relevancia", "mais_comentarios", "mais_apoios"].freeze
  DOMAINS = {
    "cidadonos.org.br" => { :id => 5 },
    "varzea2022.sp.gov.br" => { :id => 3 }
  }

  has_many :inspirations
  has_many :proposals, :class_name => "Proposta"
  has_many :locais, :as => :responsavel, :dependent => :destroy, :include => [ :estado, :cidade, :bairro ]
  has_many :prizes, :class_name => "CompetitionPrize"
  alias_method :competition_prizes, :prizes

  accepts_nested_attributes_for :locais, :allow_destroy => true

  validates_presence_of :title, :short_description, :long_description, :author_description, :start_date, :inspiration_phase, :proposals_phase, :support_phase, :joining_phase, :announce_phase, :regulation, :awards, :image

  mount_uploader :image, ImageUploader
  as_enum :current_phase, PHASES

  attr_accessible :title, :short_description, :long_description, :author_description, :start_date, :finished,
    :inspiration_phase, :proposals_phase, :support_phase, :joining_phase, :announce_phase,
    :image_cache, :regulation, :awards, :partners, :published, :locais_attributes, :image

  scope :published, where(:published => true)
  scope :started, lambda { where('start_date <= ?', Date.today) }
  scope :unfinished, published.where(:finished => false)
  scope :finished, published.where(:finished => true)
  scope :running, started.unfinished
  scope :desc, order("created_at DESC")

  def to_param
    "#{id} #{title}".parameterize
  end

  def set_default_phases
    PHASES.each do |phase|
      send "#{phase}=", 18
    end
  end

  def future_phase?(phase)
    PHASES.index(current_phase) < PHASES.index(phase)
  end

  def phase_enabled?(phase)
    send(phase) > 0
  end

  def phase_over?(phase)
    finished? or PHASES.index(phase) < PHASES.index(current_phase)
  end

  def supports_allowed?
    current_phase == :support_phase or finished?
  end

  def inspirations_allowed?
    current_phase == :inspiration_phase
  end

  def proposals_allowed?
    current_phase == :proposals_phase
  end

  def comments_allowed?
    current_phase == :proposals_phase or finished?
  end

  def joinings_allowed?
    current_phase == :joining_phase
  end

  def enabled_phases
    PHASES.select { |p| phase_enabled? p }
  end

  def calculate_current_phase
    phase = enabled_phases.find { |p| remaining_days_from(p) > 0 }

    self.finished = phase.nil?
    self.current_phase = phase || enabled_phases.last
  end

  def remaining_days
    remaining_days_from PHASES.last
  end

  def remaining_days_in_current_phase
    remaining_days_from current_phase
  end

  def remaining_days_from(phase)
    [(expiration_date_from(phase) - Date.today).to_i, 0].max
  end

  def expiration_date_from(phase)
    days = 0
    PHASES.each do |p|
      days += send(p)
      break if p == phase
    end
    start_date.to_date + days
  end

  def before_expiration_time_from(phase)
    (expiration_date_from(phase) - 1).end_of_day
  end

  def prizes_with_defined_winning_topic
    competition_prizes.where("winning_topic_id IS NOT NULL")
  end

  def participants
    User.where("
      id IN (SELECT topicos.user_id FROM topicos WHERE topicos.competition_id = :competition_id) OR
      id IN (SELECT inspirations.user_id FROM inspirations WHERE inspirations.competition_id = :competition_id) OR
      id IN (SELECT comments.user_id FROM comments INNER JOIN topicos ON topicos.competition_id = :competition_id AND comments.commentable_id = topicos.id AND commentable_type = 'Topico') OR
      id IN (SELECT adesoes.user_id FROM adesoes INNER JOIN topicos ON topicos.competition_id = :competition_id AND adesoes.topico_id = topicos.id) OR
      id IN (SELECT seguidos.user_id FROM seguidos INNER JOIN topicos ON topicos.competition_id = :competition_id AND seguidos.topico_id = topicos.id)
    ", :competition_id => id)
  end

  def participants_count
    Rails.cache.fetch(["Competition#participants_count", id], :expires_in => 10.minutes) do
      participants.count
    end
  end

  def human_current_phase
    I18n.t("activerecord.attributes.competition.#{current_phase}")
  end

  def to_s
    title
  end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  respond_to :html

  inherit_resources

  with_options :cache_path => Proc.new { |c| { :params => c.params, :flash => c.flash.to_hash } }, :layout => false, :if => Proc.new { current_user.nil? || !current_user.admin? } do |c|

    c.with_options :expires_in => 2.minutes do |c|
      c.caches_action :index
    end

    c.with_options :expires_in => 5.minutes do |c|
      c.caches_action :regulation
      c.caches_action :prizes
      c.caches_action :partners
    end
  end

  before_filter :set_competition_meta_tags, :except => :index
  before_filter :redirect_unpublished, :only => :show

  def index
    @running_competitions  = Competition.running.includes(:locais)
    @finished_competitions = Competition.finished.includes(:locais)
  end

  def regulation
  end

  def prizes
    @prizes = resource.prizes
  end

  def partners
  end

  def show
    @phase = params[:phase].try(:to_sym) || resource.current_phase
    if resource.future_phase?(@phase)
      redirect_to competition_path(resource)
    else
      case @phase
        when :inspiration_phase
          phase_with_inspirations
        when :announce_phase
          phase_with_prizes
        else
          phase_with_proposals
      end
      @activities = resource.activities_summary
      render @phase
    end
  end

  protected

  def set_competition_meta_tags
    set_meta_tags CompetitionMetaTags.for(request, resource)
  end

  def redirect_unpublished
    redirect_to(competitions_path, :alert => "Este concurso não está publicado") unless resource.published?
  end

  def phase_with_inspirations
    @inspirations = resource.inspirations.paginate(:page => params[:page], :per_page => 10).order('created_at DESC')
  end

  def phase_with_prizes
    @prizes = resource.prizes_with_defined_winning_topic
  end

  def phase_with_proposals
    @tag = Tag.find(params[:tag_id]) unless params[:tag_id].blank?

    @proposals = resource.proposals.includes(:user)
    proposals_order
    proposals_tags
    proposals_paginate
  end

  def proposals_order
    @proposals = case params[:order]
      when "recentes"
        @proposals.order("topicos.created_at DESC")
      when "mais_comentarios"
        @proposals.order("topicos.comments_count DESC")
      when "mais_apoios"
        @proposals.order("topicos.adesoes_count DESC")
      else
        params[:order] = "relevancia"
        @proposals.order("topicos.relevancia DESC")
    end
  end

  def proposals_tags
    @proposals = @proposals.maybe_tagged_with(@tag)
    @tags = @proposals.tags_to_cloud
  end

  def proposals_paginate
    @proposals = @proposals.paginate(:page => params[:page], :per_page => 10)
  end

  def collection
    @competitions ||= end_of_association_chain.running
  end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper

  def remaining_days_countdown_in phase
    if @competition.current_phase == phase
      days = @competition.remaining_days_in_current_phase
      if days == 1
        content_tag("p", Time.now.day_countdown, :class => "qtd day_countdown") +
        content_tag("p", "restantes", :class => "sobre")
      else
        content_tag("p", days, :class => "qtd") +
        content_tag("p", "dias restantes", :class => "sobre")
      end
    end
  end

  def phase_over_or_current?(competition, phase)
    return false unless competition.current_phase
    competition.phase_over?(phase) or competition.current_phase == phase
  end
end

app/views/competitions/_commom_sidebar.html.erb
<% if @tags %>
  <h3>Tags relevantes</h3>
  <div class="cloud">
    <% tag_cloud(@tags) do |tag, c| -%>
      <span class="<%= c %>">
        <%= link_to_competition_with_context tag.name, :tag_id => tag.id %></span>
    <% end -%>
  </div>
<% end %>

<%= render "shared/activities_feed", :activities => @activities %>
<%= render "shared/addthis_toolbox" %>

app/views/competitions/_competition_banner.html.erb
<div class="competition_banner rounded clearfix">
  <h2><%= @competition.title %></h2>

  <% if @competition.phase_over? @phase %>
    <h3 class="short_description">Esta fase já está finalizada.</h3>
  <% else %>
    <h3 class="short_description"><%= t("competition.short_description.#{@phase}") %></h3>
  <% end %>

  <%= render "phases", :competition => @competition, :active_phase => @phase %>

  <%= image_tag @competition.image.url(:small), :class => "thumb" %>

  <%= markdown @competition.short_description  %>

  <p><%= link_to_function "Ver mais", "jQuery('#longDescription').toggle('slide')" %></p>

  <div id="longDescription">
    <h3>Sobre o Concurso <span><%= link_to_function "[fechar]", "jQuery('#longDescription').toggle('slide')" %></span></h3>

    <%= markdown @competition.long_description  %>

    <h3>Quem propõe:</h3>
    <%= markdown @competition.author_description  %>
  </div>
</div>

app/views/competitions/_navigation_links.html.erb
<ul class="navigation_links">
  <li><%= link_to "Prêmios", prizes_competition_path(competition) %></li>
  <li><%= link_to "Regulamento", regulation_competition_path(competition) %></li>
  <li><%= link_to "Parceiros", partners_competition_path(competition) %></li>
</ul>

app/views/competitions/_prize_panel.html.erb
<div class="clearfix prize_panel">
  <div class="offered">
   <%= render "users/ficha_do_usuario", :usuario => prize.offerer, :options => {} %>
  </div>
  <div class="description"><%= prize.description %></div>
</div>

app/views/competitions/_proposals_resume.html.erb
<div class="resumo rounded clearfix">
  <%= remaining_days_countdown_in phase %>
  <p class="qtd"><%= @competition.proposals.count %></p>
  <p class="sobre">propostas</p>
  <p class="qtd"><%= @competition.participants_count %></p>
  <p class="sobre">participantes</p>
  <%= render "navigation_links", :competition => @competition %>
</div>

app/views/competitions/_running_competitions.html.erb
<li class="competition running_competition rounded clearfix">
  <div class="locais"><%= descrever_locais(competition.locais) %></div>
  <h3><%= link_to competition.title, competition_path(competition) %></h3>
  <div class="competition_summary">
    <%= image_tag competition.image.url(:small), :class => "thumb" %>
    <div class="description">
      <p><%= truncate(competition.short_description, :length => 200) %></p>
      <%= link_to "Ver mais", competition_path(competition), :class => "link_mini" %>
    </div>
  </div>
  <%= render "competitions/phases", :competition => competition, :active_phase => competition.current_phase %>
  <div class="resumo resumo_de_atividades_active clearfix">
    <p class="qtd"><%= competition.remaining_days %></p>
    <p class="sobre">dias restantes</p>
    <p class="qtd"><%= competition.proposals.count %></p>
    <p class="sobre">propostas</p>
    <p class="qtd"><%= competition.participants_count %></p>
    <p class="sobre">participantes</p>
  </div>
</li>

app/views/competitions/announce_phase.html.erb
<div class="grid_16 alpha omega">
  <div class="grid_11 alpha competition_full">
    <%= render "competition_banner" %>

    <ul id="breadcrumb" class="clearfix">
      <li>
        <h1>Prêmios</h1>
      </li>
    </ul>

    <% if @prizes.size > 0 %>
      <div class="topicos_list prizes_list">
        <% @prizes.each do |prize| %>
          <div class="rounded prize">
            <h3><%= prize.name %></h3>
            <div class="topico proposta clearfix">
              <% if prize.winning_topic %>
                <%= topico(prize.winning_topic) %>
              <% end %>
            </div>
            <%= render 'prize_panel', :prize => prize %>
          </div>
        <% end %>
      </div>
    <% else %>
    <div class="rounded rounded_beige">
      <p>Nossa equipe está definindo os ganhadores. Em breve você conhecerá o resultado deste concurso.</p>
    </div>
    <% end %>
  </div>

  <div class="grid_5 omega sidebar">
    <%= render "proposals_resume", :phase => :announce_phase %>
    <%= render "commom_sidebar" %>
  </div>
</div>

app/views/competitions/index.html.erb
<% if @running_competitions.size > 0 %>
<div class="competitions_list">
  <h1 class="title">Concursos ativos</h1>
  <ul class="running_competitions">
    <%= render :partial => "competitions/running_competitions",
      :collection => @running_competitions, :as => :competition %>
  </ul>
</div>
<% end %>

<% if @finished_competitions.size > 0 %>
<div class="competitions_list">
  <h1 class="title">Concursos concluídos</h1>
  <ul class="finished_competitions">
    <%= render :partial => "competitions/finished_competitions",
      :collection => @finished_competitions, :as => :competition %>
  </ul>
</div>
<% end %>

app/views/competitions/inspiration_phase.html.erb
<div class="grid_16 alpha omega">
  <div class="grid_11 alpha competition_full">
    <%= render :partial => 'competition_banner' %>

    <ul id="breadcrumb" class="clearfix">
      <li>
        <h1>Inspirações</h1>
      </li>
    </ul>

    <% if @inspirations.present? %>
      <%= render "inspirations/inspirations", :inspirations => @inspirations %>
    <% else %>
      <div class="rounded">
        <p>Este concurso não possui nenhuma inspiração.</p>
        <% if @competition.inspirations_allowed? %>
          <p>Seja o primeiro!</p>
          <p>Que iniciativas podem inspirar os participantes nesse concurso?<br />Traga imagens, sons e texto. Seja visual.</p>
          <p>Clique no botão <%= link_to "Inspirar", new_competition_inspiration_path(@competition), :class => "btn btn-pink btn-mini" %> e participe deste concurso.
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="grid_5 omega sidebar">
    <% if @competition.inspirations_allowed? %>
      <%= link_to "Inspirar", new_competition_inspiration_path(@competition), :class => "btn btn-pink btn-large" %>
      <p>Mande uma inspiração para este concurso.</p>
    <% end %>

    <div class="resumo rounded clearfix">
      <%= remaining_days_countdown_in :inspiration_phase %>
      <p class="qtd"><%= @competition.inspirations.count %></p>
      <p class="sobre">inspirações</p>
      <p class="qtd"><%= @competition.participants_count %></p>
      <p class="sobre">participantes</p>
      <%= render "navigation_links", :competition => @competition %>
    </div>

    <%= render "commom_sidebar" %>
  </div>
</div>

app/views/competitions/partners.html.erb
<div class="grid_12 alpha static_page">
  <div class="rounded">
    <h2>Parceiros</h2>
    <%= markdown @competition.partners %>
  </div>
</div>
<%= render "competitions/menu_sidebar" %>

app/views/competitions/prizes.html.erb
<div class="grid_12 alpha static_page">
  <div class="rounded">
    <h2>Prêmios</h2>
    <%= markdown @competition.awards %>
    <div class="prizes_list">
      <% @competition.prizes.each do |prize| %>
        <h3><%= prize.name %></h3>
        <%= render "prize_panel", :prize => prize %>
      <% end %>
    </div>
  </div>
</div>
<%= render "competitions/menu_sidebar" %>

app/views/competitions/proposals_phase.html.erb
<div class="grid_16 alpha omega">
  <div class="grid_11 alpha competition_full">
    <%= render :partial => 'competition_banner' %>
    <%= render :partial => 'proposals_list' %>
  </div>

  <div class="grid_5 omega sidebar">
    <% if @competition.proposals_allowed? %>
      <%= link_to "Propor!", new_competition_proposal_path(@competition), :class => "btn btn-blue btn-large" %>
      <p>Mande uma proposta para este concurso.</p>
    <% end %>

    <%= render "proposals_resume", :phase => :proposals_phase %>
    <%= render "commom_sidebar" %>
  </div>
</div>

app/views/competitions/regulation.html.erb
<div class="grid_12 alpha static_page">
  <div class="rounded">
    <h2>Regulamento</h2>
    <%= markdown @competition.regulation %>
  </div>
</div>
<%= render :partial => "competitions/menu_sidebar" %>

app/views/competitions/support_phase.html.erb
<div class="grid_16 alpha omega">
  <div class="grid_11 alpha competition_full">
    <%= render "competition_banner" %>
    <%= render "proposals_list" %>
  </div>

  <div class="grid_5 omega sidebar">
    <%= render "proposals_resume", :phase => :support_phase %>
    <%= render "commom_sidebar" %>
  </div>
</div>