config/routes.rb
Rails.application.routes.draw do

  # Letter opener
  if Rails.env.development? or Rails.env.staging?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Configurações
  types_of_topico       = Regexp.new("(topicos|#{Topico::TYPES.map(&:last).map(&:tableize).join('|')})")
  orders_of_topico      = Regexp.new("(#{Topico::ORDERS.join('|')})")
  feeds_of_topico       = Regexp.new("(#{Topico::FEEDS.join('|')})")

  types_of_user         = Regexp.new("(#{User::TYPES.map(&:last).map(&:tableize).join('|')})")
  orders_of_user        = Regexp.new("(#{User::ORDERS.join('|')})")

  estado = Regexp.new('[a-z]{2}')
  cidade = Regexp.new('[a-zA-Z\-]+')

  match "/*robots.txt", :to => redirect("/robots.txt")

  #=================================================#
  #  Admin
  #=================================================#
  match "/admin", :to => "admin/painel#index", :as => "admin"

  namespace :admin do

    resources :macro_tags

    resources :tags do
      collection do
        get :maistags
        post :set_tag_name
        post :novastags
        get :transferencia
        post :transferencia_post
        post :transfere_drag
        match :separar
      end
    end
    resources :topicos do
      member do
        post :comment_destroy
      end
    end
    resources :configuracoes do
      collection do
        get :update_check_box
        post :salvar
      end
    end
    resources :comentarios
  end

  #=============================================================================================#
  #  Aplicação para o USUÁRIO: Login, logout, cadastro, confirmação, perfil, observatorio etc.
  #=============================================================================================#

  devise_for :users,
    :controllers => {
      :registrations => "devise/custom/registrations",
      :passwords => "devise/custom/passwords",
      :sessions => "devise/custom/sessions",
      :omniauth_callbacks => "omniauth_callbacks"
    }

  match "/usuario/completar_cadastro" => "users#complete", :as => "completar_cadastro"
  match "/vincular/:user_id_criptografado" => "users#vincular", :as => "vincular"
  match "/solicitar_vinculacao/:organizacao_id" => "users#solicitar_vinculacao", :as => "solicitar_vinculacao"
  match "/usuarios/solicitar_cadastro_entidade" => "users#solicitar_cadastro_entidade", :as => "solicitar_cadastro_entidade"
  match "/users/:id/waiting_for_confirmation" => "users#waiting_for_confirmation", :as => "waiting_for_confirmation"
  match "/users/save" => "users#save"

  # Navegação por usuários
  match "/usuarios(/:user_type)(/estado/:estado_abrev)(/cidade/:cidade_slug)(/bairro/:bairro_id)(/:order)" => "users#index",
    :constraints => {
      :user_type => types_of_user,
      :estado_abrev => estado,
      :cidade_slug => cidade,
      :bairro_id => /\d+/,
      :order => orders_of_user
    },
    :as => "usuarios"

  # Perfil do usuário: dados pessoais, local, avatar, tópicos, comentários, funcionários, etc.
  match "/perfil/:id" => "users#show", :constraints => { :id => /\d+/ }, :as => "perfil"
  match "/perfil/:id.:format" => "users#show", :constraints => { :id => /\d+/ }, :as => "perfil_rss"
  match "/perfil/:id.:format" => "users#show", :constraints => { :id => /\d+/ }, :as => "perfil_json"
  match "/perfil/:id/mensagem" => "users#mensagem", :constraints => { :id => /\d+/ }, :as => "perfil_mensagem"

  match "/perfil/:id/propostas" => "users#show", :type => "propostas", :constraints => { :id => /\d+/ }, :as => "perfil_propostas"
  match "/perfil/:id/problemas" => "users#show", :type => "problemas", :constraints => { :id => /\d+/ }, :as => "perfil_problemas"
  match "/perfil/:id/comentarios" => "users#show", :type => "comments", :constraints => { :id => /\d+/ }, :as => "perfil_comentarios"
  match "/perfil/:id/apoios" => "users#show", :type => "adesoes", :constraints => { :id => /\d+/ }, :as => "perfil_apoios"
  match "/perfil/:id/seguindo" => "users#show", :type => "seguidos", :constraints => { :id => /\d+/ }, :as => "perfil_seguindo"

  match "/perfil/dados_basicos" => "users#edit", :as => "edit_user"
  match "/perfil/localizacao" => "users#localizacao"
  match "/perfil/avatar" => "avatar#new", :as => "new_avatar"
  match "/perfil/avatar/resize" => "avatar#resize"
  match "/perfil/avatar/salvar" => "avatar#create"
  match "/perfil/avatar/remover" => "avatar#destroy"
  match "/perfil/descadastrar" => "users#descadastrar", :as => "descadastrar"
  match "/perfil/confirma_descadastro" => "users#confirma_descadastro", :as => "confirma_descadastro"

  # Meu Observatório
  match "/meu-observatorio/novo" => "observatorios#new", :as => "novo_observatorio"
  match "/meu-observatorio/criar" => "observatorios#create", :as => "criar_observatorio"
  match "/meu-observatorio/editar" => "observatorios#edit", :as => "editar_observatorio"
  match "/meu-observatorio/salvar" => "observatorios#salvar", :as => "salvar_observatorio"
  match "/meu-observatorio/comentarios(/:page)" => "observatorios#comentarios", :as => "observatorio_comentarios"
  match "/meu-observatorio/apoios(/:page)" => "observatorios#apoios", :as => "observatorio_apoios"
  match "/meu-observatorio(/:page)" => "observatorios#index", :as => "observatorio"
  match "/meu-observatorio/:action/:id" => "observatorios"

  #==============================================#
  #   Tópicos
  #==============================================#

  match "/:topico_type(/estado/:estado_abrev)(/cidade/:cidade_slug)(/bairro/:bairro_id)(/tags/:tag_id)(/de/:user_type)(/:order(/:rss))(/:page)" => "topicos#index",
    :constraints => {
      :topico_type  => types_of_topico,
      :estado_abrev => estado,
      :cidade_slug  => cidade,
      :bairro_id    => /\d+/,
      :tag_id       => /\d+/,
      :user_type    => types_of_user,
      :order        => orders_of_topico,
      :rss          => feeds_of_topico,
      :page         => /\d+/
    },
    :defaults => {
      :topico_type => "topicos"
    },
    :as => "topicos"

  match "/topicos/mostrar_similares" => "topicos#mostrar_similares", :as => "topico_mostrar_similares"

  # Novo tópico
  match "/topicos/criar/:type" => "topicos#new", :via => :get, :as => "novo_topico"
  match "/topicos/criar/:type/localizar" => "topicos#new_localizar", :via => :post, :as => "localizar_novo_topico"
  match '/competitions/:competition_id/proposal/new' => 'topicos#new', :type => "proposta", :as => :new_competition_proposal
  match "/topicos/salvar" => "topicos#create", :as => "criar_topico"

  # Tópico
  match "/topico/:topico_slug" => "topicos#show", :as => "topico"
  match "/topico/:topico_slug/editar" => "topicos#edit", :as => "editar_topico"
  match "/topico/:topico_slug/salvar" => "topicos#update", :as => "salvar_topico"

  match "/topico/:topico_slug/aderir" => "topicos#aderir", :as => "aderir"
  match "/topico/:topico_slug/seguir" => "topicos#seguir", :as => "seguir"

  # Localização de tópico
  match "/topico/:topico_slug/localizacao" => "topicos#localizacao", :as => "topico_localizacao"

  # Editar Tags de tópico
  match "/topico/:topico_slug/tags" => "topicos#tags", :as => "topico_localizacao"
  match "/topico/:topico_slug/tags_by_link" => "topicos#tags_by_link", :as => "topico_localizacao"

  # Imagens de tópico
  match "/topico/:topico_slug/imagens" => "imagens#index", :as => "topico_imagens"
  match "/topico/:topico_slug/imagens/nova" => "imagens#create", :as => "topico_nova_imagem"
  match "/topico/:topico_slug/imagens/editar/:id" => "imagens#edit", :as => "topico_editar_imagem"
  match "/topico/:topico_slug/imagens/remover/:id" => "imagens#destroy", :as => "topico_remover_imagem"

  # Links de tópico
  match "/topico/:topico_slug/links" => "links#index", :as => "topico_links"
  match "/topico/:topico_slug/links/novo" => "links#create", :as => "topico_novo_link"
  match "/topico/:topico_slug/links/remover/:id" => "links#destroy", :as => "topico_remover_link"

  # Denunciar
  match "/topico/:topico_slug/denunciar" => "topicos#denunciar", :as => "topico_denunciar"

  # Comments
  match "/comments/processar" => "comments#processar", :as => "processar_comment"
  match "/comments/create" => "comments#create", :as => "create_comment"
  match "/comments/set_comentario_body/:id" => "comments#set_comentario_body"

  #======================================#
  #  Competitions
  #======================================#
  get '/competitions/:id(/fase/:phase(/tags/:tag_id))(/:order)(/page/:page)' => 'competitions#show',
    :constraints => CompetitionConstraint, :as => :competition

  resources :competitions, :only => [:index] do
    resources :inspirations

    member do
      get 'regulation'
      get 'prizes'
      get 'partners'
    end
  end

  #======================================#
  #  Joining Topics
  #======================================#
  match "/joining_topics/new/:topico_id", :controller => "joining_topics", :action => "new",
    :constraints => {:topico_id => /\d+/},
    :as => :new_joining_topic

  resources :joining_topics, :only => [:show, :create] do
    member do
      get :preview

      get :title_edit
      put :title_update

      get :description_edit
      put :description_update

      put :suggest
      put :reject
      put :aprove
    end
  end

  #======================================#
  #  General
  #======================================#

  # Tags
  match "/tags/auto_complete_responder" => "tags#auto_complete_responder", :as => "auto_complete_responder_tags"

  # Busca do Google
  match "/busca-google" => "busca#index", :as => "busca_google"

  # Static pages
  match "/static_pages/:name" => 'static_pages#show', :as => :static_page, :format => false

  # Locais
  match "/locais/cidades_li_for_ul" => "locais#cidades_li_for_ul"
  match "/locais/bairros_li_for_ul" => "locais#bairros_li_for_ul"
  match "/locais/cidades_options_for_select(/:first_option)" => "locais#cidades_options_for_select", :as => :cidades_options_for_select

app/models/observatorio.rb
class Observatorio < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :tags,
                          :join_table => "observatorios_tem_tags",
                          :table_name => "observatorios_tem_tags"

  has_many :locais, :as => :responsavel, :dependent => :destroy

  validates_presence_of :nome
  validates_associated :locais

  attr_accessible :tag_ids, :receber_email

  # Dada uma tag (name!), mostrar quais observatorios usam-na.
  scope :com_tag, lambda { |tag_name|
    if tag_name.blank?
      {}
    else
      {
        :joins => "INNER JOIN observatorios_tem_tags INNER JOIN tags ON (observatorios_tem_tags.observatorio_id = observatorios.id) AND (observatorios_tem_tags.tag_id = tags.id)",
        :conditions => [ "tags.name = ?", tag_name ]
      }
    end
  }

  # Descreve automaticamente o observatorio
  # criado: Ex.: PP dos temas x, y, z em A e B e C.
  def auto_descricao
    str = "Propostas e problemas "
    # TAGS...
    if not self.tags.empty?
      str += (self.tags.size > 1) ? "dos temas " : "do tema "
      str += "<span class=\"tags\">"
      str += self.tags.collect{ |t| t.name }.join(", ")
      str += "</span>"
    end
    # LOCAIS...
    if not self.locais.empty?
      tmp = []
      for local in self.locais
        aux  = " em <b>#{local.cidade.nome}</b> (#{local.cidade.estado.abrev})"
        aux += ", no bairro <i>#{local.bairro.nome}</i>" if local.bairro
        tmp << aux
      end
      str += tmp.join(" e ")
    end
    return str
  end

  # Retorna os IDs dos topicos
  # filtrados pelo observatorio
  def topico_ids
    Topico.com_tags(self.tag_ids).nos_locais(self.locais).all(:select => "topicos.id")
  end

  # Retorna Array com atividades (Apoios + Comentarios) 
  # de todos os topicos filtrados pelo observatorio.
  # Se informado "depois_de", apenas depois dessa data;
  # Se não, TODAS!
  def atividades(depois_de = nil)
    atividades = []

    topicos = Topico.com_tags(self.tag_ids).nos_locais(self.locais).apos_o_dia(depois_de).all(:order => "topicos.id DESC")
    atividades += topicos

    topico_ids = Topico.com_tags(self.tag_ids).nos_locais(self.locais).all(:order => "topicos.id DESC").collect{ |t| t.id }
    if topico_ids and !topico_ids.empty?
      # Comentarios feitos
      depois_de_sql = depois_de.nil? ? "" : " AND created_at >= '#{depois_de}'"
      Comment.find(:all,
                   :conditions => ["commentable_type = 'Topico' AND 
                                    commentable_id IN (?) #{depois_de_sql}", topico_ids],
                   :order => "created_at DESC").each { |c| atividades << c }

      # Apoios/Adesoes
      Adesao.dos_topicos(topico_ids).depois_de(depois_de).all.each { |a| atividades << a }
    end

    return atividades.sort!{ |x, y| x.created_at <=> y.created_at }.reverse!
  end
end

app/controllers/observatorios_controller.rb
class ObservatoriosController < ApplicationController
  before_filter :authenticate_user!, :except => [ :index ]
  before_filter :obter_observatorio, :except => [ :new, :create ]
  before_filter :obter_contadores, :only => [ :index, :comentarios, :apoios ]

  def index
    # @topicos = Topico.scoped(@observatorio.contexto).paginate(:per_page => 5, :page => params[:page], :order => "topicos.id DESC") if @observatorio
    @topicos = Topico.com_tags(@observatorio.tag_ids).nos_locais(@observatorio.locais).paginate(:per_page => 50, :page => params[:page], :order => "topicos.id DESC") if @observatorio

    unless current_user
      session[:observatorio] = 'observatorio'
    end

  end

  def new
    @observatorio = current_user.observatorios.build
    @tags = Tag.find(:all, :order => "name ASC")
  end

  def create
   #render :text => params.inspect
   @observatorio = current_user.observatorios.build(params[:observatorio])
   @observatorio.nome = "Observatório 1"
   if @observatorio.save
     if params[:local]
       params[:local].each do |p|
         #logger.debug ">>>>>>>> #{p.inspect}"
         @observatorio.locais.create(p[1])
       end
     end
     flash[:notice] = "Observatório criado com sucesso"
     redirect_to observatorio_url
   else
     @tags = Tag.find(:all, :order => "name ASC")
     render :action => "new"
   end
  end

  def edit
    @tags = Tag.find(:all, :order => "name ASC")
  end

  def salvar
    if @observatorio.update_attributes(params[:observatorio])
      @observatorio.locais.clear
      if params[:local]
        params[:local].each do |p|
          @observatorio.locais.create(p[1])
        end
      end
      flash[:notice] = "Observatório atualizado com sucesso"
      redirect_to observatorio_url
    else
      @tags = Tag.find(:all, :order => "name ASC")
      render :action => "edit"
    end
  end

  def comentarios
    @comentarios = Comment.paginate(:conditions => [ "commentable_type = 'Topico' AND commentable_id IN (?)", @topico_ids ],
                                    :order => "id DESC",
                                    :per_page => 50,
                                    :page => params[:page])
    render :action => "index"
  end

  def apoios
    @apoios = Adesao.dos_topicos(@observatorio.topico_ids.collect{ |t| t.id }).paginate(:order => "id DESC", :per_page => 50, :page => params[:page])
    render :action => "index"
  end

  protected

  def obter_observatorio
    @observatorio = user_signed_in? ? current_user.observatorios.first : nil
    @topico_ids = @observatorio ? Topico.com_tags(@observatorio.tag_ids).nos_locais(@observatorio.locais).all.collect{ |t| t.id } : []
  end

  def obter_contadores
    if @observatorio
      @topicos_count = @observatorio.topico_ids.size
      @comentarios_count = Comment.count(:conditions => [ "commentable_type = 'Topico' AND commentable_id IN (?)", @topico_ids ])
      @apoios_count = Adesao.dos_topicos(@topico_ids).size
    end
  end

end

app/views/observatorios/_abas.html.erb
<ul class=" clearfix tabs_secondary">
  <li><%= link_to "Propostas e problemas (#{@topicos_count})",
                  observatorio_url(:page => nil),
                  :class => action_name == "index" ? "active" : "" %></li>
  <li><%= link_to "Comentários (#{@comentarios_count})",
                  observatorio_comentarios_url(:page => nil),
                  :class => action_name == "comentarios" ? "active" : "" %></li>
  <li><%= link_to "Apoios (#{@apoios_count})",
                  observatorio_apoios_url(:page => nil),
                  :class => action_name == "apoios" ? "active" : "" %></li>
</ul>

app/views/observatorios/_apoios.html.erb
<ul id="atividades" class="feeds_big"><% @apoios.each do |apoio| -%>  <%= descreve(apoio, nil) %><% end -%></ul><%= will_paginate @apoios %>

app/views/observatorios/_comentarios.html.erb
<ul id="atividades" class="feeds_big">
<% @comentarios.each do |comentario| -%>
  <%= descreve(comentario, nil) %>
<% end -%>
</ul>
<%= will_paginate @comentarios %>

app/views/observatorios/_contexto_do_observatorio.html.erb
<div class="contexto_do_observatorio">
  <h3 class="nome">Contexto</h3>
  <p class="link"><%= link_to "[Editar]", editar_observatorio_url %></p>
  <div class="rounded rounded_beige">
<!-- LOCAIS -->
    <p class="locais"><strong>Onde</strong></p>
<% if !@observatorio.locais.empty? %>
    <ul>
<% @observatorio.locais.each do |local| -%>
      <li>
<% if local.tem_bairro? -%>
        <%= local.bairro.nome %>, <%= local.bairro.cidade.nome %> - <%= local.bairro.cidade.estado.abrev %>
<% elsif local.tem_cidade? -%>
        <%= local.cidade.nome %> - <%= local.cidade.estado.abrev %>
<% elsif local.tem_estado? -%>
        <%= local.estado.abrev %>
<% end -%>
      </li>
<% end %>
    </ul>
<% else -%>
    <p>Todo o site</p>
<% end -%>

<!-- TAGS:temas -->
    <p class="tags"><strong>Temas</strong></p>
<% if !@observatorio.tags.empty? -%>
    <ul>
<% @observatorio.tags.all(:order => "tags.name ASC").each do |tag| -%>
      <li>
        <%= tag.name %>
      </li>
<% end -%>
    </ul>
<% else %>
    <p>Todos os temas</p>
<% end %>
  </div>
</div> <!-- contexto_do_observatorio -->

app/views/observatorios/_empty_design_logado.html.erb
<div class="grid_10 alpha static_page">
  <h2>Olá <%= current_user.nome %>, configure o seu observatório</h2>

  <div class="rounded">
    <p>Acompanhe com seu <strong>observatório</strong> o que acontece nos <strong>temas</strong> e nas <strong>regiões</strong> que mais lhe interessam.</p>
    <p>Criar seu observatório é simples:</p>
    <ol>
      <li>Defina os temas e as regiões de seu interesse</li>
      <li>Acompanhe num mesmo lugar propostas, problemas, comentários e apoios</li>
      <li>Receba semanalmente as novidades por e-mail</li>
    </ol>
    <br />
    <div class="action">
      <%= link_to "Criar", novo_observatorio_url, :class => "btn" %>
    </div>
  </div>
</div>
<div class="grid_6 omega">
	<%= image_tag('binoculo.jpg')%>
</div>

app/views/observatorios/_empty_design_nao_logado.html.erb
<h2>Observe temas e regiões do seu interesse</h2>
<div class="grid_10 alpha static_page">

  <div class="rounded">
    <p>Acompanhe com seu <strong>observatório</strong> o que acontece nos <strong>temas</strong> e nas <strong>regiões</strong> que mais lhe interessam.</p>
    <p>Como funciona o observatório?</p>
    <ol>
      <li>Defina os temas e as regiões de seu interesse</li>
      <li>Acompanhe num mesmo lugar propostas, problemas, comentários e apoios</li>
      <li>Receba semanalmente as novidades por e-mail</li>
    </ol>
    <p>Este recurso é exclusivo para <strong>usuários cadastrados</strong>.</p>
    <br />
    <div class="action">
      <a class="btn" href="<%= new_user_session_url %>">Faça seu Login</a>
      <span>OU</span>
      <a class="btn" href="<%= new_user_registration_url %>">Cadastre-se Agora!</a>
    </div>
  </div>
</div>
<div class="grid_6 omega ">
  <div class="rounded">
  	<%= image_tag('binoculo.jpg') %>
  </div>
</div>

app/views/observatorios/_form.html.erb
<div class="rounded clearfix">
  <div id="tags" class="grid_16 alpha omega">
    <h3>1. Escolha os temas a serem observados</h3>
    <div class="grid_8 alpha">
      <!-- Precisa para funcionar o HABTM com checkboxes. -->
      <%= hidden_field_tag "observatorio[tag_ids][]", "" %>
      <%= select_tag "observatorio[tag_ids][]",
                     options_for_select(@tags.collect { |t| [ t.name, t.id ] }, @observatorio.tag_ids),
                     :multiple => true %>
    </div>
    <div class="grid_8 omega">
      <p>
        Para selecionar vários temas, pressione a tecla <span class="tecla">CTRL</span> e clique nos temas desejados.
      </p>
    </div>
  </div>
  <div id="onde" class="grid_16 alpha omega">
    <h3>2. Escolha as regiões a serem observadas</h3>
    <p>
      Se quiser, você pode escolher <strong>cidades</strong> e <strong>bairros</strong> a serem observados.
    </p>
    <p style="margin:0 0 10px 0;">
      <%= link_to_remote image_tag("icones/add.png") + " Escolher mais uma região",
                         :url => {
                           :controller => "locais",
                           :action => "escolher_uma_regiao"
                         },
                         :before => "$('spinner').show()",
                         :complete => "$('spinner').hide()",
                         :html => {
                           :class => "adicionar",
                           :title => "Adicione uma cidade ou bairro às regiões que você deseja observar"
                         } %>
      <span id="spinner" style="display:none;"><%= image_tag("spinners/dots-white.gif") %></span>
    </p>
    <div id="locais" class="grid_16 alpha omega">

    </div>
  </div>
  <div id="opcoes" class="grid_16 alpha omega">
    <h3>3. Quer receber as novidades por e-mail?</h3>
    <p>
      <label>
      <%= check_box :observatorio, :receber_email %> Sim, quero receber as novidades em e-mails semanais
      </label>
    </p>
  </div>
</div>

app/views/observatorios/_lista_de_topicos.html.erb
<div class="grid_16 alpha omega">
  <h2>Observatório</h2>
  <div class="grid_12 alpha">
    <%= render :partial => "observatorios/abas" %>
<% if action_name == "index" -%>
    <%= render :partial => "observatorios/topicos" %>
<% elsif action_name == "comentarios" -%>
    <%= render :partial => "observatorios/comentarios" %>
<% elsif action_name == "apoios" -%>
    <%= render :partial => "observatorios/apoios" %>
<% end -%>
  </div>
  <div class="grid_4 omega">
    <%= render :partial => "contexto_do_observatorio" %>
  </div>
</div>

app/views/observatorios/_seletor_de_local.html.erb
<div id="seletor_de_local_<%= d %>" class="seletor_de_local">
  <%= link_to_function image_tag("icones/delete.png"),
                       "$('seletor_de_local_#{d}').remove();",
                       :title => "Remover este local das regiões observadas" %>
  <%= hidden_field_tag "local[#{d}][pais_id]", 1 %>
  <%= select_tag "local[#{d}][estado_id]", "<option></option>#{estados_options}".html_safe  %>
  <span id="spinner_<%= d %>" class="spinner" style="display: none;"><%= image_tag("spinners/spinner.gif") %></span>
  <%= select_tag "local[#{d}][cidade_id]", "<option></option>#{cidades_options}".html_safe, :class => "cidade" %>
  <%= link_to_function "Escolher um bairro",
                       "$('local_#{d}_seletor_de_bairro').show(); $('link_escolher_#{d}_seletor_de_bairro').hide();",
                       :id => "link_escolher_#{d}_seletor_de_bairro",
                       :style => (bairro_id ? "display: none;" : "" ) %>
  <span id="local_<%= d %>_seletor_de_bairro"<% if !bairro_id %> style="display: none;"<% end %>>
    <%= select_tag "local[#{d}][bairro_id]", "<option></option>#{bairros_options}".html_safe, :class => "bairro" %>
    <%= link_to_function "Quero em toda a cidade",
                         "$('local_#{d}_seletor_de_bairro').hide(); $('local_#{d}_bairro_id').selectedIndex = -1; $('link_escolher_#{d}_seletor_de_bairro').show();",
                         :id => "link_fechar_#{d}_seletor_de_bairro" %>
  </span>
  <%= observe_field "local_#{d}_estado_id",
                    :update => "local_#{d}_cidade_id",
                    :url => {
                      :controller => "locais",
                      :action => "cidades_options_for_select"
                    },
                    :with => "estado_id",
                    :before => "$('spinner_#{d}').show();",
                    :complete => "$('spinner_#{d}').hide(); $('local_#{d}_cidade_id').selectedIndex = -1; $('local_#{d}_bairro_id').selectedIndex = -1;" -%>
  <%= observe_field "local_#{d}_cidade_id",
                    :update => "local_#{d}_bairro_id",
                    :url => {
                      :controller => "locais",
                      :action => "bairros_options_for_select"
                    },
                    :with => "cidade_id",
                    :complete => "$('local_#{d}_bairro_id').selectedIndex = -1;" -%>
</div>

app/views/observatorios/_topicos.html.erb
<%= topicos(@topicos, :mostrar_local => true, :titulo_max_chars => 90) %><%= will_paginate @topicos %>

app/views/observatorios/edit.html.erb
<% title "Editar observatório" %>
<h2>Editar observatório</h2>
<%= error_messages_for :observatorio %>
<%= form_tag salvar_observatorio_url do %>
  <%= render :partial => "form" %>
  <div>
    <%= submit_tag "Salvar", :class => "btn" %> ou
    <%= link_to "Cancelar", observatorio_url %>
  </div>
<% end %>

app/views/observatorios/index.html.erb
<% title "Meu observatório" %>
<% if user_signed_in? -%>
  <% if current_user.observatorios.empty? -%>
    <%= render :partial => "empty_design_logado" %>
  <% else -%>
    <%= render :partial => "lista_de_topicos" %>
  <% end -%>
<% else -%>
  <%= render :partial => "empty_design_nao_logado" %>
<% end -%>

app/views/observatorios/new.html.erb
<% title "Criar observatório" %>
<h1>Configurar observatório</h1>
<%= error_messages_for :observatorio %>
<%= form_tag criar_observatorio_url do %>
  <%= render :partial => "form" %>
  <div>
    <%= submit_tag "Salvar", :class => 'btn' %> ou
    <%= link_to "Cancelar", observatorio_url %>
  </div>
<% end %>