config/routes.rb
Rails.application.routes.draw do

  # Letter opener
  if Rails.env.development? or Rails.env.staging?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Configurações
  types_of_topico       = Regexp.new("(topicos|#{Topico::TYPES.map(&:last).map(&:tableize).join('|')})")
  orders_of_topico      = Regexp.new("(#{Topico::ORDERS.join('|')})")
  feeds_of_topico       = Regexp.new("(#{Topico::FEEDS.join('|')})")

  types_of_user         = Regexp.new("(#{User::TYPES.map(&:last).map(&:tableize).join('|')})")
  orders_of_user        = Regexp.new("(#{User::ORDERS.join('|')})")

  estado = Regexp.new('[a-z]{2}')
  cidade = Regexp.new('[a-zA-Z\-]+')

  match "/*robots.txt", :to => redirect("/robots.txt")

  #=================================================#
  #  Admin
  #=================================================#
  match "/admin", :to => "admin/painel#index", :as => "admin"

  namespace :admin do

    resources :macro_tags

    resources :tags do
      collection do
        get :maistags
        post :set_tag_name
        post :novastags
        get :transferencia
        post :transferencia_post
        post :transfere_drag
        match :separar
      end
    end
    resources :topicos do
      member do
        post :comment_destroy
      end
    end
    resources :configuracoes do
      collection do
        get :update_check_box
        post :salvar
      end
    end
    resources :comentarios
  end

  #=============================================================================================#
  #  Aplicação para o USUÁRIO: Login, logout, cadastro, confirmação, perfil, observatorio etc.
  #=============================================================================================#

  devise_for :users,
    :controllers => {
      :registrations => "devise/custom/registrations",
      :passwords => "devise/custom/passwords",
      :sessions => "devise/custom/sessions",
      :omniauth_callbacks => "omniauth_callbacks"
    }

  match "/usuario/completar_cadastro" => "users#complete", :as => "completar_cadastro"
  match "/vincular/:user_id_criptografado" => "users#vincular", :as => "vincular"
  match "/solicitar_vinculacao/:organizacao_id" => "users#solicitar_vinculacao", :as => "solicitar_vinculacao"
  match "/usuarios/solicitar_cadastro_entidade" => "users#solicitar_cadastro_entidade", :as => "solicitar_cadastro_entidade"
  match "/users/:id/waiting_for_confirmation" => "users#waiting_for_confirmation", :as => "waiting_for_confirmation"
  match "/users/save" => "users#save"

  # Navegação por usuários
  match "/usuarios(/:user_type)(/estado/:estado_abrev)(/cidade/:cidade_slug)(/bairro/:bairro_id)(/:order)" => "users#index",
    :constraints => {
      :user_type => types_of_user,
      :estado_abrev => estado,
      :cidade_slug => cidade,
      :bairro_id => /\d+/,
      :order => orders_of_user
    },
    :as => "usuarios"

  # Perfil do usuário: dados pessoais, local, avatar, tópicos, comentários, funcionários, etc.
  match "/perfil/:id" => "users#show", :constraints => { :id => /\d+/ }, :as => "perfil"
  match "/perfil/:id.:format" => "users#show", :constraints => { :id => /\d+/ }, :as => "perfil_rss"
  match "/perfil/:id.:format" => "users#show", :constraints => { :id => /\d+/ }, :as => "perfil_json"
  match "/perfil/:id/mensagem" => "users#mensagem", :constraints => { :id => /\d+/ }, :as => "perfil_mensagem"

  match "/perfil/:id/propostas" => "users#show", :type => "propostas", :constraints => { :id => /\d+/ }, :as => "perfil_propostas"
  match "/perfil/:id/problemas" => "users#show", :type => "problemas", :constraints => { :id => /\d+/ }, :as => "perfil_problemas"
  match "/perfil/:id/comentarios" => "users#show", :type => "comments", :constraints => { :id => /\d+/ }, :as => "perfil_comentarios"
  match "/perfil/:id/apoios" => "users#show", :type => "adesoes", :constraints => { :id => /\d+/ }, :as => "perfil_apoios"
  match "/perfil/:id/seguindo" => "users#show", :type => "seguidos", :constraints => { :id => /\d+/ }, :as => "perfil_seguindo"

  match "/perfil/dados_basicos" => "users#edit", :as => "edit_user"
  match "/perfil/localizacao" => "users#localizacao"
  match "/perfil/avatar" => "avatar#new", :as => "new_avatar"
  match "/perfil/avatar/resize" => "avatar#resize"
  match "/perfil/avatar/salvar" => "avatar#create"
  match "/perfil/avatar/remover" => "avatar#destroy"
  match "/perfil/descadastrar" => "users#descadastrar", :as => "descadastrar"
  match "/perfil/confirma_descadastro" => "users#confirma_descadastro", :as => "confirma_descadastro"

  # Meu Observatório
  match "/meu-observatorio/novo" => "observatorios#new", :as => "novo_observatorio"
  match "/meu-observatorio/criar" => "observatorios#create", :as => "criar_observatorio"
  match "/meu-observatorio/editar" => "observatorios#edit", :as => "editar_observatorio"
  match "/meu-observatorio/salvar" => "observatorios#salvar", :as => "salvar_observatorio"
  match "/meu-observatorio/comentarios(/:page)" => "observatorios#comentarios", :as => "observatorio_comentarios"
  match "/meu-observatorio/apoios(/:page)" => "observatorios#apoios", :as => "observatorio_apoios"
  match "/meu-observatorio(/:page)" => "observatorios#index", :as => "observatorio"
  match "/meu-observatorio/:action/:id" => "observatorios"

  #==============================================#
  #   Tópicos
  #==============================================#

  match "/:topico_type(/estado/:estado_abrev)(/cidade/:cidade_slug)(/bairro/:bairro_id)(/tags/:tag_id)(/de/:user_type)(/:order(/:rss))(/:page)" => "topicos#index",
    :constraints => {
      :topico_type  => types_of_topico,
      :estado_abrev => estado,
      :cidade_slug  => cidade,
      :bairro_id    => /\d+/,
      :tag_id       => /\d+/,
      :user_type    => types_of_user,
      :order        => orders_of_topico,
      :rss          => feeds_of_topico,
      :page         => /\d+/
    },
    :defaults => {
      :topico_type => "topicos"
    },
    :as => "topicos"

  match "/topicos/mostrar_similares" => "topicos#mostrar_similares", :as => "topico_mostrar_similares"

  # Novo tópico
  match "/topicos/criar/:type" => "topicos#new", :via => :get, :as => "novo_topico"
  match "/topicos/criar/:type/localizar" => "topicos#new_localizar", :via => :post, :as => "localizar_novo_topico"
  match '/competitions/:competition_id/proposal/new' => 'topicos#new', :type => "proposta", :as => :new_competition_proposal
  match "/topicos/salvar" => "topicos#create", :as => "criar_topico"

  # Tópico
  match "/topico/:topico_slug" => "topicos#show", :as => "topico"
  match "/topico/:topico_slug/editar" => "topicos#edit", :as => "editar_topico"
  match "/topico/:topico_slug/salvar" => "topicos#update", :as => "salvar_topico"

  match "/topico/:topico_slug/aderir" => "topicos#aderir", :as => "aderir"
  match "/topico/:topico_slug/seguir" => "topicos#seguir", :as => "seguir"

  # Localização de tópico
  match "/topico/:topico_slug/localizacao" => "topicos#localizacao", :as => "topico_localizacao"

  # Editar Tags de tópico
  match "/topico/:topico_slug/tags" => "topicos#tags", :as => "topico_localizacao"
  match "/topico/:topico_slug/tags_by_link" => "topicos#tags_by_link", :as => "topico_localizacao"

  # Imagens de tópico
  match "/topico/:topico_slug/imagens" => "imagens#index", :as => "topico_imagens"
  match "/topico/:topico_slug/imagens/nova" => "imagens#create", :as => "topico_nova_imagem"
  match "/topico/:topico_slug/imagens/editar/:id" => "imagens#edit", :as => "topico_editar_imagem"
  match "/topico/:topico_slug/imagens/remover/:id" => "imagens#destroy", :as => "topico_remover_imagem"

  # Links de tópico
  match "/topico/:topico_slug/links" => "links#index", :as => "topico_links"
  match "/topico/:topico_slug/links/novo" => "links#create", :as => "topico_novo_link"
  match "/topico/:topico_slug/links/remover/:id" => "links#destroy", :as => "topico_remover_link"

  # Denunciar
  match "/topico/:topico_slug/denunciar" => "topicos#denunciar", :as => "topico_denunciar"

  # Comments
  match "/comments/processar" => "comments#processar", :as => "processar_comment"
  match "/comments/create" => "comments#create", :as => "create_comment"
  match "/comments/set_comentario_body/:id" => "comments#set_comentario_body"

  #======================================#
  #  Competitions
  #======================================#
  get '/competitions/:id(/fase/:phase(/tags/:tag_id))(/:order)(/page/:page)' => 'competitions#show',
    :constraints => CompetitionConstraint, :as => :competition

  resources :competitions, :only => [:index] do
    resources :inspirations

    member do
      get 'regulation'
      get 'prizes'
      get 'partners'
    end
  end

  #======================================#
  #  Joining Topics
  #======================================#
  match "/joining_topics/new/:topico_id", :controller => "joining_topics", :action => "new",
    :constraints => {:topico_id => /\d+/},
    :as => :new_joining_topic

  resources :joining_topics, :only => [:show, :create] do
    member do
      get :preview

      get :title_edit
      put :title_update

      get :description_edit
      put :description_update

      put :suggest
      put :reject
      put :aprove
    end
  end

  #======================================#
  #  General
  #======================================#

  # Tags
  match "/tags/auto_complete_responder" => "tags#auto_complete_responder", :as => "auto_complete_responder_tags"

  # Busca do Google
  match "/busca-google" => "busca#index", :as => "busca_google"

  # Static pages
  match "/static_pages/:name" => 'static_pages#show', :as => :static_page, :format => false

  # Locais
  match "/locais/cidades_li_for_ul" => "locais#cidades_li_for_ul"
  match "/locais/bairros_li_for_ul" => "locais#bairros_li_for_ul"
  match "/locais/cidades_options_for_select(/:first_option)" => "locais#cidades_options_for_select", :as => :cidades_options_for_select

app/controllers/admin/topicos_controller.rb
class Admin::TopicosController < Admin::AdminController

  # DELETE /tags/1
  # DELETE /tags/1.xml
  def destroy
    @topico = Topico.find(params[:id])
    @topico.destroy
    flash[:info] = "Tópico removido com sucesso."
    redirect_to root_url
  end

end

app/helpers/topicos_helper.rb
module TopicosHelper

  # Infos de cada topico
  def topico(topico, options = {})
    my_options = {
      :titulo_max_chars => 100,
      :mostrar_local => false,
      :mostrar_atividades => true,
      :show_supports => true
    }
    options = my_options.merge!(options)
    render :partial => "topicos/topico",
           :locals => {
             :topico => topico,
             :options => options
           }
  end

  # Lista de Topicos
  def topicos(topicos, options = {})
    my_options = {
      :link_in_tags => true,
      :paginate => false,
      :show_supports => true
    }
    options = my_options.merge!(options)
    render :partial => "topicos/topicos",
           :locals => {
             :topicos => topicos,
             :options => options
           }
  end

  def comentario(comentario, options = {})
    render :partial => "comments/comentario",
           :locals => { :comentario => comentario }
  end

  def comentarios(comentarios, options = {})
    render :partial => "comments/comentarios",
           :locals => { :comentarios => comentarios }
  end

  def comentarios_estatisticas(comentarios, topico, options = {})
    render :partial => "comments/comentarios_estatisticas",
           :locals => {
             :comentarios => comentarios,
             :topico => topico
           }
  end

  def comentarios_estatisticas_media_por_tempo(from, total, options={})
    from_time = from.to_time
    to_time = Time.now.to_time
    distance_in_minutes = (((to_time - from_time).abs)/60).round
    media = (distance_in_minutes/total).round
    case media
      when 0..1             then
        outra_media = total
        outra_media = (total/distance_in_minutes).round if (distance_in_minutes != 0)
        return "#{pluralize(outra_media,'comentário')} por minuto"
      when 2..59            then return "1 comentário a cada hora"
      when 60..1439         then return "mais de 1 comentário por dia"
      when 1440..4319       then return "1 comentário a cada 3 dias"
      when 4320..8639       then return "mais de 1 comentário por semana"
      when 8640..10079      then return "1 comentário por semana"
      when 10080..41759     then return "mais de 1 comentário por mês"
      when 41760..43199     then return "1 comentário por mês"
      when 43200..126000    then return "cerca de 1 comentário a cada 3 meses"
      when 86400..525599    then return "1 comentário por ano"
      else                       return "menos de 1 comentário por ano"
    end
  end

  def show_coauthor?
    @joining and @joining.topico_to == @topico and @topico.user !=  @joining.coauthor
  end

  def outer_topico_joined
    if @joining.topicos_from[0] == @topico
      @joining.topicos_from[1]
    else
      @joining.topicos_from[0]
    end
  end

  def joining_topico_to?
    @joining and @joining.topico_to == @topico
  end
end

app/views/topicos/_cloud.html.erb
<% if tags.present? %>
  <% if params[:tag_id] %>
    <h3>Temas relacionados</h3>
  <% end %>
  <div class="cloud">
  <h3>Tags</h3>
  <% tag_cloud_contexto(tags) do |tag, c| -%>
    <span class="<%= c %>"><%= link_to_topicos_with_context tag.name, :tag_id => tag.id %></span>
  <% end -%>
  </div>
<% else -%>
  <p class="no_tags rounded rounded_beige">
    Ainda não há temas (ou tags...) cadastradas.<br />
    <span class="call2action">Indique uma questão e associe-a aos temas apropriados!</span><br />
    <span class="hint">Use os botões no topo à direita:
    <br/>
    “Aponte um problema” e “Crie uma proposta”.</span>
  </p>
<% end -%>

app/views/topicos/_competition_addthis.html.erb
<div id="divulgacao" style="display:none;">
  <div id="divulgue" class="addthis_toolbox">
    <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js"></script>
    <script type="text/javascript">
      var addthis_config = {
           ui_language: "pt" /*,
           services_expanded: "bebo,misterwong,netvibes" */
      }
    </script>
    <div class="vertical">
      <a class="addthis_button_google_plusone_share">Google Plus</a>
      <a class="addthis_button_twitter">Twitter</a>
      <a class="addthis_button_facebook">Facebook</a>
    </div>
    <p><%= link_to_function "Cancelar", "Effect.BlindUp('divulgacao', {duration:0.4})" %></p>
  </div>
</div>

    

app/views/topicos/_content_buttons.html.erb
<ul id="comentar_ou_fazer_campanha" class="clearfix">
  <% if not @from_joining and @topico.comments_allowed? %>
  <li>
    <div id="botao_de_comentar" class="botao_de_acao">
      <%= link_to_function(raw("<i class='btn-icon-megaphone'></i>") + "Comente",
                           visual_effect(:toggle_blind, "novo_comentario", :duration => 1)) %>
    </div>
  </li>
  <% end %>

  <!-- topico in competition -->
  <% if @topico.competition.present? %>
    <% if @topico.can_be_supported? %>
      <li>
        <div id="botao_de_apoiar" class="botao_de_acao">
          <%= link_to(raw("<i class='btn-icon-hand-up'></i>") + (@topico.is_apoiado(current_user) ? "Deixe de apoiar" : "Apoie!"),
                      aderir_path(@topico)) %>
        </div>
      </li>
    <% end %>
    <% if @topico.can_be_joined?  %>
      <li>
        <div id="botao_de_unir" class="botao_de_acao">
          <%= link_to(raw("<i class='btn-icon-union'></i>") + 'Sugira uma União',
                new_joining_topic_path(:topico_id => @topico.id)
              ) %>
        </div>
      </li>
    <% end %>
  <!-- topico simples -->
  <% else %>
    <li>
      <div id="botao_de_campanha" class="botao_de_acao">
        <%= link_to_function(raw("<i class='btn-icon-arroba'></i>") + "Faça uma campanha",
                             visual_effect(:toggle_blind, "divulgacao", :duration => 0.6)) %>
      </div>
    </li>
  <% end %>
</ul>

<!-- faça uma campanha - addthis -->
<% unless @topico.competition.present? %>
<div class="grid_12 alpha omega">
  <%= render :partial => "divulgacao_addthis",
             :locals => {
               :mostrar => false,
               :name_suffix => ""
             } -%>
</div>
<% end -%>

<div class="grid_12 alpha omega">
  <%= render :partial => "comments/novo_comentario" %>
</div>

app/views/topicos/_filtros.html.erb
<div id="filtros">
  <h3>Filtrar</h3>

  <%= filtro("Estado",
             @estados.collect { |estado_abrev, name, total|
               link_to_topicos_with_context "#{name} (#{total})",
                                            :estado_abrev => estado_abrev.downcase,
                                            :cidade_slug => nil,
                                            :bairro_id => nil
             },
             :expandido => true) if @estados.present? %>

  <%= filtro("Cidade",
             @cidades.collect { |estado_abrev, cidade_slug, name, total|
               link_to_topicos_with_context "#{name} (#{total})",
                                            :estado_abrev => estado_abrev.downcase,
                                            :cidade_slug => cidade_slug,
                                            :bairro_id => nil
             },
             :expandido => true) if @cidades.present? %>

  <%= filtro("Bairro",
             @bairros.collect { |estado_abrev, cidade_slug, bairro_id, name, total|
               link_to_topicos_with_context "#{name} (#{total})",
                                            :estado_abrev => estado_abrev.downcase,
                                            :cidade_slug => cidade_slug,
                                            :bairro_id => bairro_id
             },
             :expandido => true) if @bairros.present? %>

  <%= filtro("Proponente",
             @topicos_user_stats.collect { |type, total|
               link_to_topicos_with_context("#{type.underscore.pluralize.humanize.gsub(/(publicos)/,'públicos')} (#{total})",
                                            { :user_type => type.to_s.underscore.pluralize.downcase },
                                            :class => "#{type.to_s.underscore.downcase}")
             }) if @topicos_user_stats.present? %>

  <%= filtro("Tipo",
             @topicos_stats.collect { |type, total|
               link_to_topicos_with_context("#{type} (#{total})",
                                            { :topico_type => type.pluralize.downcase },
                                            :class => type.downcase)
             }) if @topicos_stats.present? %>

</div> <!-- filtros -->

app/views/topicos/_form_topico.html.erb
<% title "#{action_name.humanize}" -%>
<%= error_messages_for :topico,
                       :header_message => "Opa!" -%>

<div class="grid_11 clearfix">
  <fieldset>
    <%= f.hidden_field :competition_id %>
    <ol>
      <li>
        <%= label_tag :titulo, "Título" %>
        <span class="ajuda">Escreva uma única frase que resuma a questão. <b>Evite</b> mencionar o local (há uma etapa para a localização).</span><br />
        <%= f.text_field :titulo, :class => "titulo", :rows => 2 %>
        <% if controller.action_name != "edit" %>
          <%= observe_field "topico_titulo",
                          :url => topico_mostrar_similares_path,
                          :with => "'type=#{@topico.type}&search=' + value" %>
        <% end %>
      </li>
      <li id="similares"><!-- espaco reservado para listar topicos similares --></li>
      <li>
        <%= label_tag :descricao, "Descrição" %>
        <span class="ajuda">Descreva de forma sucinta e objetiva <%= @topico.nome_do_tipo(:artigo => :definido) if @topico %>. Prefira 1 ou 2 parágrafos. Links, imagens, outros arquivos e demais referências poderão ser acrescidos depois.</span><br />
        <%= f.text_area :descricao, :class => "descricao", :rows => 8 %>
      </li>
      <% if (controller.action_name != "edit") -%>
      <li>
        <%= label_tag :tags, "Tags" %>
        <span class="ajuda">
          Indique os <b>temas</b> relacionados a esta questão, separando-os com <b>vírgula</b>.<br />
          Ex: <span id="tags_possiveis">saúde, remédios, mortalidade infantil</span>
        </span><br/>
        <%= text_field_with_auto_complete :topico, :tags_com_virgula,
                                          {
                                            :class => "tags texto",
                                            :autocomplete => "off"
                                          },
                                          {
                                            :url => auto_complete_responder_tags_path,
                                            :tokens => ",",
                                            :min_chars => 2,
                                            :param_name => "tag"
                                          } %><br />
        <% if @tags -%>
        <br />
        <h4>Ou escolha suas tags clicando nos <b>temas mais populares</b> listados abaixo:</h4>
        <div id="populares" class="cloud">
          <% tag_cloud_contexto(@tags) do |tag, c| -%>
            <span class="<%= c %>"><%= link_to_function tag.name, "acrescentaTagComVirgula('#{tag.name}')" %></span>
          <% end %>
        <div>
        <% end #if @tags -%>
      </li>
      <% end -%>
    </ol>
  </fieldset>
</div>
<script type="text/javascript">
//<![CDATA[
function acrescentaTagComVirgula(tag_name) {
  $('topico_tags_com_virgula').value = $('topico_tags_com_virgula').value + tag_name + ',';
}
//]]>
</script>

app/views/topicos/_lista_de_usuarios_relacionados.html.erb
<%= lista_relacionados(users) %>

app/views/topicos/_portal_odm.html.erb
<% if estado and cidade -%>
<div style="margin-top:20px; text-align:center; line-height:15px;">
	<p style="margin-bottom:10px">Veja os <strong>Objetivos do Milênio</strong> em<br />
	<strong><%= cidade.nome %></strong></p>
	<p><a title="Conheça a cidade de <%= cidade.nome %> no portal ODM: clique!" href="http://www.portalodm.com.br/relatorios/<%= estado.abrev.downcase %>/<%= cidade.slug %>" target="_blank"><%= image_tag('selo_ODM_4x2.png', :alt => 'Selo ODM') %></a></p>
</div>
<% end -%>

app/views/topicos/_splash_competition.html.erb
<div class="rounded splash_competition">
  <strong>Visite o concurso</strong>
  <h4><%= link_to @topico.competition.title, competition_path(@topico.competition) %></h4>
  <%= link_to (image_tag @topico.competition.image.url(:small)), competition_path(@topico.competition) %>
  <%= render "competitions/navigation_links", :competition => @topico.competition %>
</div>

app/views/topicos/_sugerir_tags.html.erb
<%=
  (tags).map do |tag|
    content_tag :a, tag, :href => "#", :onclick => "acrescentaTagComVirgula('#{tag}'); return false"
  end.join(", ").html_safe
%>

app/views/topicos/_topicos_relacionados.html.erb
<% if topicos_relacionados.present? -%>
<ul>
<% topicos_relacionados.each do |topico| %>
  <li class="<%= topico.display_name.underscore %>">
    <p class="titulo">
      <%= link_to truncate(topico.titulo, :length => 80),
                  topico_url(:topico_slug => topico.to_param),
                  :title => topico.titulo %>
    </p>
    <p class="detalhes">
      <span><%= topico.display_name %></span>
      <%= topico.display_name == "Problema" ? "informado" : "feita" %>
      por <%= topico.user.nome %>
    </p>
  </li>
<% end -%>
</ul>
<% else %>
<p>
  Não possui tópicos relacionados<br />
</p>
<% end %>

app/views/topicos/complete.html.erb
<h1>Complete seu cadastro!</h1>

<%= error_messages_for :user_dado %>
<%= form_for :user_dado, :url => "/completar_cadastro" do |f| -%>
<p><%= label_tag 'email' %><br/>
<b><%= @user.email %></b></p>

<p><%= label_tag 'nome' %><br/>
<%= f.text_field :nome %></p>

<p><%= label_tag 'sexo' %><br/>
<%= f.radio_button :sexo, 'm' %> masculino <br />
<%= f.radio_button :sexo, 'f' %> feminino <br /></p>

<p><%= label_tag 'aniversario', 'Aniversário' %><br/>
<%= f.date_select :aniversario, :order => [:day, :month, :year], 
                                :start_year => 1920, 
                                :end_year => 1.year.ago.year,
                                :default => 18.years.ago %></p>

<p><%= submit_tag 'Salvar' %></p>
<% end -%>

app/views/topicos/index.html.erb
<%
  if params[:topico_type] != "topicos"
    title params[:topico_type].camelize
  else
    title "Propostas e problemas"
  end
  title @bairro.nome if @bairro
  title @cidade.nome if @cidade
  title @estado.abrev if @estado
%>

<div class="grid_12 alpha">
  <%= render :partial => "topicos/breadcrumb" %>

  <div id="contador_e_ordenador" class="clearfix rounded rounded_beige">
    <ul id="ordenador">
      <li><%= link_to_topicos_with_context "Relevância", :order => "relevancia" %></li>
      <li><%= link_to_topicos_with_context "Recentes", :order => "recentes" %></li>
      <li><%= link_to_topicos_with_context "Antigos", :order => "antigos" %></li>
      <li><%= link_to_topicos_with_context "Mais comentários", :order => "mais_comentarios" %></li>
      <li><%= link_to_topicos_with_context "Mais apoios", :order => "mais_apoios" %></li>
    </ul>
  </div>

  <div class="grid_4 alpha sidebar">
    <div id="resumo_de_atividades" class="resumo clearfix rounded">
      <p class="qtd"><%= @contadores[:propostas] %></p>
      <p class="sobre">Propostas</p>
      <p class="qtd"><%= @contadores[:problemas] %></p>
      <p class="sobre">Problemas</p>
      <p class="qtd"><%= @contadores[:comentarios] %></p>
      <p class="sobre">Comentários</p>
      <p class="qtd"><%= @contadores[:adesoes] %></p>
      <p class="sobre">Apoios</p>
    </div>
    <%= render :partial => "topicos/cloud", :locals => { :tags => @tags } %>
    <%= render :partial => "topicos/portal_odm", :locals => { :cidade => @cidade, :estado => @estado } %>
  </div>

  <div class="grid_8 omega">
    <%= topicos(@topicos, :titulo_max_chars => 58, :mostrar_local => true) %>
    <%= will_paginate @topicos %>
  </div>

</div>

<div id="barra_lateral" class="grid_4 omega sidebar">
  <%= render :partial => "shared/action_buttons" %>
  <% if signed_in? and current_user.local and current_user.local.cidade %>
  <h3>Da sua cidade</h3>
  <%= link_to_topicos_with_context "Questões de #{current_user.local.descricao}",
                                  {:estado_abrev => current_user.local.estado.abrev.downcase,
                                  :cidade_slug => current_user.local.cidade.slug,
                                  :bairro_id => nil,
                                  :user_type => nil},
                                  :class => "btn btn-mini-extended" %>
  <% end %>
  <%= render :partial => "filtros" %>
</div>

app/views/topicos/index.xml.erb
<% if @topicos and (@topicos.size > 0) -%>
<% @topicos.each_with_index do |topico, i| -%>
<% if (i < 10) -%>
<item>
  <title><%= topico.titulo %></title>
  <link>
    <%= topico_url(:topico_slug => topico.to_param) %>
  </link>
  <% if @tag -%>
  <category><%= @tag.name %></category>
  <% end -%>
  <% if topico.imagens and (topico.imagens.size > 0) -%>
  <image>
    <% if topico.imagens[0].legenda.blank? -%>
    <title>Imagem de <%= topico.titulo %></title>
    <% else -%>
    <title><%= topico.imagens[0].legenda %></title>
    <% end -%>
    <url><%= request.protocol %><%= request.host %><%= topico.imagens[0].public_filename %></url>
    <link><%= request.url %></link>
  </image>
  <% end -%>
  <description>
  <%= topico.descricao %>
  </description>
  <pubDate><%=l topico.updated_at, :format => "%a, %d %b %Y %H:%M:%S -0300" %></pubDate>
  <guid>
    <%= topico_url(:topico_slug => topico.to_param) %>
  </guid>
</item>
<% end -%>
<% end -%>
<% end %>

app/views/topicos/new.html.erb
<% case @topico.type %>
  <% when "Problema" %>
    <h2>Aponte um problema</h2>
  <% when "Proposta" %>
    <% unless @competition %>
    <h2>Faça sua proposta</h2>
    <% else %>
    <h2>Faça sua proposta para o concurso<br> <%= @competition.title %></h2>
    <p>Case você deseje criar uma proposta que não pertence a este concurso, <%= link_to "clique aqui", novo_topico_path(:type => "proposta") %>.</p>
    <% end %>
<% end %>

<%= render :partial => "topicos/passos_para_novo_topico" %>

<div class="clearfix novo_topico">
  <div class="grid_16 alpha omega" id="form_novo_topico">
    <div class="rounded clearfix">
      <%= form_for :topico, :url => localizar_novo_topico_path do |f| -%>
        <%= render :partial => "form_topico", :locals => { :f => f } %>
        <%= submit_tag "Continuar >", :id => "bot_continuar", :class => "btn btn-mini clearfix" %>
      <% end %>
    </div>
  </div>
  <div class="grid_5 omega">
    &nbsp;
  </div>
</div>